import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "To-do-list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
  

{
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between bg-black text-white p-4">
        <div className="p-3">
          logo
        </div>
        <div>
            <Link href="/" className="p-5 m-3 bg-gray-700 hover:bg-black text-white transition duration-300 ease-in-out border-2 border-gray-700 hover:border-red-600">home</Link> 
            <Link href="/customer_area" className="p-5 m-3 bg-gray-700 hover:bg-black text-white transition duration-300 ease-in-out border-2 border-gray-700 hover:border-red-600">area do cliente</Link> 
        </div>
      </header>
        {children}
      </body>
    </html>
  );
}
