import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "To-do-list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
  

{
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between bg-black text-white p-4">
        <div className="p-3">
          logo
        </div>
        <div className="p-3">
            <Link href="/" className="font-roboto p-5 m-2 bg-gray-500 hover:bg-gray-900 text-white transition duration-300 ease-in-out border-2 rounded-t-lg border-gray-700 hover:border-tahiti font-modal">HOME</Link> 
            <Link href="/customer_area" className="font-roboto p-5 bg-gray-500 hover:bg-gray-900 text-white transition duration-300 ease-in-out border-2 rounded-t-lg border-gray-700 hover:border-tahiti font-modal">CONFIGURAÇÕES</Link> 
        </div>
      </header>
        {children}
      </body>
    </html>
  );
}
